from setuptools import setup, Extension

signer_module = Extension(
   '_CardanoSigner',
   sources=['signer_wrap.cxx', 'signer.cpp'], # signer_wrap.cxx is going to be generated by swig
   extra_objects=["libsigner.a"] # this is the static library that we are going to link with
)

setup (
	name        = 'CardanoSigner',
	version     = '0.0',
	author      = "YOUR_NAME",
	description = "CardanoSigner swig",
	ext_modules = [signer_module],
	py_modules  = ["CardanoSigner"], # name of module that we're going import
)