[package]
name = "signer"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
cxx = "1.0"
cardano-serialization-lib = "=14.0.0"
tiny-bip39 = "2.0.0"

[build-dependencies]
cxx-build = "1.0"
