# from setuptools import setup, Extension

# signer_module = Extension(
#    '_CardanoSigner',
#    sources=['signer_wrap.cxx', 'signer.cpp'], # signer_wrap.cxx is going to be generated by swig
#    extra_objects=["libsigner.a"] # this is the static library that we are going to link with
# )

# setup (
# 	name        = 'CardanoSigner',
# 	version     = '0.0',
# 	author      = "YOUR_NAME",
# 	description = "CardanoSigner swig",
# 	ext_modules = [signer_module],
# 	py_modules  = ["CardanoSigner"], # name of module that we're going import
# )
import os
import platform
import sys

from setuptools import Extension, setup


def get_signer_extension():
    """Create an Extension object appropriate for the current platform."""
    sources = ["signer_wrap.cxx", "signer.cpp"]
    include_dirs = ['.']
    
    # Determine platform-specific settings
    system = platform.system().lower()
    extra_compile_args = []
    extra_link_args = []
    
    if system == 'linux':
        extra_compile_args = ['-std=c++11']
        libraries = ['ssl', 'crypto']
    elif system == 'darwin':  # macOS
        extra_compile_args = ['-std=c++11']
        libraries = ['ssl', 'crypto']
        if os.path.exists('/usr/local/opt/openssl/lib'):
            # Intel macOS
            include_dirs.append('/usr/local/opt/openssl/include')
            extra_link_args = ['-L/usr/local/opt/openssl/lib']
        elif os.path.exists('/opt/homebrew/opt/openssl/lib'):
            # Apple Silicon macOS
            include_dirs.append('/opt/homebrew/opt/openssl/include')
            extra_link_args = ['-L/opt/homebrew/opt/openssl/lib']
    elif system == 'windows':
        libraries = ['libcrypto', 'libssl']
        # Add Windows-specific paths if needed
    
    # Define the extension
    return Extension(
        '_CardanoSigner',
        sources=sources,
        include_dirs=include_dirs,
        extra_objects=["libsigner.a"],
        extra_compile_args=extra_compile_args,
        extra_link_args=extra_link_args,
        libraries=libraries
    )

setup(
    name='CardanoSigner',
    version='0.1.0',  # Adjust version as needed
    author='SIDAN Lab',
    author_email='tszwai@deltadefi.io',
    description='CardanoSigner Python binding',
    ext_modules=[get_signer_extension()],
    py_modules=['CardanoSigner'],
)